2020-12-31 08:00:03,428 
2020-12-31 08:00:03,428 LOG
2020-12-31 08:00:03,428 log/201231_080003 true
2020-12-31 08:00:03,429 
2020-12-31 08:00:03,431 DIR
2020-12-31 08:00:03,431 /home/mac/my/prj_new/auto/las2geotiff/dat_test/01 DSM LAS TO GEOTIFF/03_FT115 - Jln Kuala Teriang_Pantai Tengah/DSM las
2020-12-31 08:00:03,431 
2020-12-31 08:00:14,568 MERGE_PROJECT_LAS
2020-12-31 08:00:14,569 pdal pipeline --stream "/home/mac/my/prj_new/auto/las2geotiff/dat_test/01 DSM LAS TO GEOTIFF/03_FT115 - Jln Kuala Teriang_Pantai Tengah/pipe_merge_proj.json"
2020-12-31 08:00:14,569 2
2020-12-31 08:00:14,569 err
2020-12-31 08:00:14,569 duration = 11s
2020-12-31 08:00:14,569 size = ~1.01Gb
2020-12-31 08:00:14,569 
2020-12-31 08:00:14,811 CONVERT_LAS_TO_GEOTIFF
2020-12-31 08:00:14,811 pdal pipeline --stream "/home/mac/my/prj_new/auto/las2geotiff/dat_test/01 DSM LAS TO GEOTIFF/03_FT115 - Jln Kuala Teriang_Pantai Tengah/pipe_convert.json"
2020-12-31 08:00:14,812 256
2020-12-31 08:00:14,812 err
2020-12-31 08:00:14,812 duration = 0s
2020-12-31 08:00:14,812 
2020-12-31 08:00:14,813 Traceback (most recent call last):
  File "/home/mac/my/prj_new/auto/las2geotiff/r15/app/agent_las2geotiff.py", line 96, in do
    out = fix_tif.do(file_tif, file_tif_fixed)
  File "/home/mac/my/prj_new/auto/las2geotiff/r15/app/log.py", line 24, in wrapper
    name, cmd, out = func(*args, *kwargs)
TypeError: do() takes 3 positional arguments but 4 were given

